USE [master]
GO
CREATE LOGIN [PedroDBA] WITH PASSWORD=N'SenhaMuitoForteAqui' MUST_CHANGE, DEFAULT_DATABASE=[master], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO

ALTER SERVER ROLE sysadmin
ADD MEMBER PedroDBA;
GO